---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: helm-charts
  namespace: flux
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/locked: "true"
spec:
  releaseName: ghost
  chart:
    git: ssh://git@github.com/asiragusa/flux-get-started
    ref: master
    path: charts/helm-charts
  values:
    ghost_image: bitnami/ghost:1.21.5-r0

    mongodb_image_tag: 4.0.6
    mongodb_chart_version: 4.9.0

    redis_chart_version: 5.1.3
    #redis_chart_version: 9.5.0
    redis_image_tag: 4.0.12
